[package]
name = "kingdom_division"
version = "0.1.0"
authors = ["noiz354 <noiz354@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
scanner-rust = "2.0.8"